image: "buddyspencer/gickup:0.10.39@sha256:3d0dabf3180ac8d3cc1939161e8b55947d697e453abeda29bdc42bb0319a9ed1"
schedule: "0 0 * * Sun"
persistence:
  enabled: false
secret:
  enabled: false
annotations: {}
