apiVersion: v2
name: cloudflared
description: Cloudflared tunnel Helm Chart
type: application
version: 1.1.5
appVersion: "2023.3.1"
dependencies:
  - name: base
    repository: https://damoun.github.io/helm-charts
    tags:
      - damoun-base
    version: 1.x.x
maintainers:
  - name: Damien Pl√©nard
    email: damien@plenard.me
    url: https://github.com/damoun
